### ISSUE TITLE
Additional attributes?

### ISSUE THREAD

**Issue by neuhausr** [maptimemsp/nacis2015-map#12]
In the json template thus far, the POI attributes are title, address, web, poi_type, and scoop. Do people think other attributes could be useful? For example, I'm thinking about phone # and hours. These are likely available from each place's website, but it could save a few clicks.

**Comment by geospatialem** [comment]
@neuhausr Great idea, I think hours and phone number would be great additions! 

If you add in the attributes to the _places.geojson_, you can also add in the update to the _script.js_ file as well to ensure the pop-up displays the attributes (currently located between [lines 48-62](https://github.com/MaptimeMSP/nacis2015-map/blob/master/js/script.js#L48)). 

Let us know if you'd like us to tackle it when you submit the PR, too. :stuck_out_tongue:

**Comment by fawcett** [comment]
We can do that.  For the other maps like this that I have created, I have stopped at URL, which is linked in the Title in the map popup.  I have figured that over the long term, it is hard to maintain hours, etc. for all of those datasources that I don't have control over.

The way that the script code is set up though, attributes that exist for that feature show up in the popup, and if they don't exist, it doesn't throw an error.  We could add options for hours and phone to display if they exist.

Personally, I am guessing that they will go to the Web page for more details anyway, but if others feel differently, I am open to it.

**Comment by neuhausr** [comment]
I totally get that, I was just thinking of a recent trip we took and some of the info we looked for. Menu/prices were other info which is often (but not always) easy to find on the website, and not all are easy to navigate on smartphone. 

Maybe, rather than new attributes, it'd be just as easy to highlight certain key info under the scoop attribute, such as: "open late", "breakfast and lunch only", "no reservations", "always crowded", "cheap eats", " good but pricey"

**Comment by geospatialem** [comment]
Personally, I like seeing hours (esp. since some places aren't open some weekdays). In fact, I added them into the [2015 GIS/LIS conference map](http://geospatialem.github.io/conference-map/). 

The way I see it, the conference is in October, and if things get outdated, they get outdated. Luckily it's all on GitHub, so anyone can put in a PR, or create their own app in the future. Just my 2 cents :moneybag:.

But, this is our collective map. So, @neuhausr, add in what you see fit, and @fawcett and I can review/duel it out when you put in the PR! :smile:

**Comment by fawcett** [comment]
I will do no dueling...  At least not on this issue.  I say that if you think that it adds to the data, you should add an attribute for hours.  I might have actually done that for the PDX map, now that I think of it.  The trick is how to describe hours that vary by day.  

We can add the logic to the template so that if there are values for hours, they show up, and if not, nor harm.

{
      "type": "Feature",
      "properties": {
        "title": "Occidental Brewing",
        "description": "Wed-Thur(4pm-8pm), Fri(3pm-8pm), Sat(12pm-8pm), Sun(12pm-6pm)",
        "address": "6635 N Baltimore Ave, Portland, Oregon, 97203",
        "web": "http://www.occidentalbrewing.com",
        "marker-symbol": "beer",
        "marker-color": "#23344c"
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          -122.7610695362091,
          45.58895111219635
        ]
      }
    }

From https://raw.githubusercontent.com/JasonSanford/foss4g-map/gh-pages/things.geojson

**Comment by geospatialem** [comment]
I like it! :+1:

**Comment by geospatialem** [comment]
Hey @neuhausr: just checking in on your progress, were you planning on adding any additional features to the POI's?

**Comment by neuhausr** [comment]
umm, little progress to report, sorry! been busy with other life. sounds like attribute-wise, it's probably good enough so I'll close this

**Comment by geospatialem** [comment]
No worries, feel free to reopen at any time! Thanks!
